services:
  db:
    image: postgres:alpine
    volumes:
      - agroflow-db:/var/lib/postgresql/data
      - db_root:/root
    env_file: .db.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 5432:5432/tcp
    network_mode: bridge

  redis:
    image: redis:alpine
    volumes:
      - ./configs/redis.conf:/etc/redis/redis.conf
    command: /etc/redis/redis.conf
    network_mode: bridge
    ports:
      - 6379:6379/tcp

volumes:
  agroflow-db:
  db_root:
